# 将 pid 文件写入 /tmp 目录，避开 /run 的 root 权限限制
pid /tmp/nginx.pid;

events {}

http {
    # 临时文件转移到 /tmp 目录
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp_path;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;

    server {
        listen 7860;
        
        location / {
            # 修改为新的目标网站
            proxy_pass https://lexika.ai/; 
            
            proxy_ssl_server_name on;
            proxy_ssl_name lexika.ai;
            
            # 伪装头部信息
            proxy_set_header Host lexika.ai; 
            proxy_set_header Origin "https://lexika.ai";
            proxy_set_header Referer "https://lexika.ai";
            
            # 传递客户端真实信息
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_redirect https://lexika.ai/ /;
        }
    }
}
